DATASETS:
 TRAIN: ("coco_2017_train_panoptic_filtrefgumdval_with_sem_seg",) #("ade20k_instance_train",)
 TEST: ("ade20k_instance_val",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0003
  STEPS: (80000,100000)
  MAX_ITER: 150000
  CHECKPOINT_PERIOD: 20000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  IMAGE_SIZE: 1024
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "open_world_instance"
TEST:
  EVAL_PERIOD: 5000
#  EVAL_FLAG: 1
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
VERSION: 2
